services:

  autoware-multi-object-tracker:
    image: ghcr.io/thinking-cars/autoware_multi_object_tracker:latest_refactoring_ci
    environment:
      # --- name ------
      NAMESPACE: /
      NAME: autoware_multi_object_tracker
      # --- inputs ----
      DETECTED_OBJECT_LIST_TOPIC: ~/detected_object_list
      # --- outputs ---
      OBJECT_LIST_TOPIC: ~/object_list
      # --- other -----
      SERVICE_TOPIC: ~/service
      LOG_LEVEL: ${LOG_LEVEL:-info}
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      PARAMS: ${PARAMS:-/docker-ros/ws/install/autoware_multi_object_tracker/share/autoware_multi_object_tracker/config/multi_object_tracker_node.param.yaml}
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch autoware_multi_object_tracker multi_object_tracker.launch.xml \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          log_level:=$${LOG_LEVEL} \
          use_sim_time:=$${USE_SIM_TIME} \
          params:=$${PARAMS} \
          input/detection01/objects:=$${DETECTED_OBJECT_LIST_TOPIC} \
          input/detection01/channel:="detected_objects" \
          output/objects:=$${OBJECT_LIST_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/autoware_multi_object_tracker/share/autoware_multi_object_tracker/config/multi_object_tracker_node.param.yaml
