apiVersion: v2
name: autoware-multi-object-tracker
version: 1.1.1
appVersion: 1.1.1
description: Modularized multi object tracker from Autoware Universe
dependencies:
  - repository: oci://ghcr.io/openads-project/openads-helm
    name: openadservice
    version: 1.2.0
